# KEEP THE COMMENT BLOCKS EXACTLY AS PROVIDED (do not change)
def sysCall_init():
    sim = require('sim')

    # do some initialization here
    # This function will be executed once when the simulation starts
    
    # Instead of using globals, you can do e.g.:
    # self.myVariable = 21000000
    
    ######## ADD YOUR CODE HERE #######
    # Hint: Initialize the scene objects which you will require
    #       Initialize algorithm related variables here
    
    ##################################

    # --- initialization of globals (safe and robust in CoppeliaSim child scripts)
    global SIM, BODY, LEFT_JOINT, RIGHT_JOINT
    global LQR_K, WHEEL_RADIUS, MAX_MOTOR_VEL
    global velocity_linear_set_point, yaw_cmd
    global pitch_dot_filtered, velocity_angular_filtered, last_pitch
    global YAW_MAG, VEL_SETPOINT_MAG, yaw_comp_factor

    SIM = sim
    BODY = sim.getObjectHandle("body")
    LEFT_JOINT = sim.getObjectHandle("left_joint")
    RIGHT_JOINT = sim.getObjectHandle("right_joint")

    # controller parameters (same LQR_K you provided)
    LQR_K = [ -2.8404703083006493, -0.04011592828490343, -3.3368304906550407e-17, 2.2360679774997827 ]
    WHEEL_RADIUS = 0.0215
    MAX_MOTOR_VEL = 10.0 # rad/s

    # state / filters
    velocity_linear_set_point = 0.0
    yaw_cmd = 0.0
    pitch_dot_filtered = 0.0
    velocity_angular_filtered = 0.0
    last_pitch = 0.0

    # keyboard -> signal magnitudes (tweak as needed)
    YAW_MAG = 0.12
    VEL_SETPOINT_MAG = 0.0

    # yaw compensation heuristic factor (tweak if needed)
    yaw_comp_factor = 0.5

    # ensure motors start at zero
    sim.setJointTargetVelocity(LEFT_JOINT, 0)
    sim.setJointTargetVelocity(RIGHT_JOINT, 0)
    
def sysCall_actuation():
    # put your actuation code here
    # This function will be executed at each simulation time step

    ####### ADD YOUR CODE HERE ######
    # Hint: Use the error feedback and apply control algorithm here
    #       Provide the resulting actuation as input to the actuator joint
    
    # Example psuedo code:
    #   x1 = error_state_1; # Error in states w.r.t desired setpoint
    #   x2 = error_state_2;
    #   x3 = error_state_3;
    #   x4 = error_state_4;
    #   k = [gain_1 , gain_1, gain_3, gain_4];      # These gains will be generated by control algorithm. For ex: LQR, PID, etc.
    #   U = -k[1]*x1 +k[2]*x2 -k[3]*x3 +k[4]*x4;    # +/- Sign convention may differ according to implementation
    #   Set_joint_actuation(U);                     # Provide this calculated input to system's actuator

    #################################
    global SIM, LEFT_JOINT, RIGHT_JOINT
    global velocity_linear_set_point, yaw_cmd
    global YAW_MAG, VEL_SETPOINT_MAG, MAX_MOTOR_VEL

    # read integer signals set externally (remote API or a Lua helper)
    up_val = SIM.getIntegerSignal('key_up')
    down_val = SIM.getIntegerSignal('key_down')
    left_val = SIM.getIntegerSignal('key_left')
    right_val = SIM.getIntegerSignal('key_right')

    up = 1 if up_val is not None and up_val != 0 else 0
    down = 1 if down_val is not None and down_val != 0 else 0
    left = 1 if left_val is not None and left_val != 0 else 0
    right = 1 if right_val is not None and right_val != 0 else 0

    # setpoint & yaw based on signals (same behavior as your original)
    if up == 1:
        velocity_linear_set_point = VEL_SETPOINT_MAG
    elif down == 1:
        velocity_linear_set_point = -VEL_SETPOINT_MAG
    else:
        velocity_linear_set_point = 0.0

    if left == 1:
        yaw_cmd = +YAW_MAG
    elif right == 1:
        yaw_cmd = -YAW_MAG
    else:
        yaw_cmd = 0.0

    # compute controller output (wheel angular velocity)
    vel = calculate_lqr_velocity()

    # apply yaw differential and clamp
    vel_l = clamp(vel + yaw_cmd, -MAX_MOTOR_VEL, MAX_MOTOR_VEL)
    vel_r = clamp(vel - yaw_cmd, -MAX_MOTOR_VEL, MAX_MOTOR_VEL)

    SIM.setJointTargetVelocity(LEFT_JOINT, vel_l)
    SIM.setJointTargetVelocity(RIGHT_JOINT, vel_r)


def sysCall_sensing():
    global SIM, BODY, LEFT_JOINT, RIGHT_JOINT
    global pitch_dot_filtered, velocity_angular_filtered, last_pitch
    global yaw_comp_factor

    # Get full orientation in euler angles
    ori = SIM.getObjectOrientation(BODY, -1)
    pitch_raw = ori[0] if (ori is not None and len(ori) > 0) else 0.0
    yaw_angle = ori[2] if (ori is not None and len(ori) > 2) else 0.0  # z-axis rotation

    # Get angular velocities
    lin_vel, ang_vel = SIM.getObjectVelocity(BODY)
    pitch_dot = ang_vel[0] if (ang_vel is not None and len(ang_vel) > 0) else 0.0
    yaw_rate = ang_vel[2] if (ang_vel is not None and len(ang_vel) > 2) else 0.0  # z-axis angular velocity

    # Wheel velocities
    vel_left = SIM.getJointVelocity(LEFT_JOINT)
    vel_right = SIM.getJointVelocity(RIGHT_JOINT)
    if vel_left is None: vel_left = 0.0
    if vel_right is None: vel_right = 0.0
    wheel_avg = (vel_left + vel_right) / 2.0
    wheel_diff = vel_left - vel_right

    # Compensate pitch reading based on yaw angle
    # This helps maintain stability during turns
    compensation_factor = 0.15  # Adjust this value as needed
    pitch_compensated = pitch_raw * math.cos(yaw_angle) - compensation_factor * abs(yaw_rate)

    # Additional yaw compensation from keyboard input
    left_sig = SIM.getIntegerSignal('key_left')
    right_sig = SIM.getIntegerSignal('key_right')
    yaw_key = (1 if (left_sig is not None and left_sig != 0) else 0) - (1 if (right_sig is not None and right_sig != 0) else 0)

    # Combine both compensations
    pitch_corrected = pitch_compensated - (yaw_comp_factor * (wheel_diff * 0.01 + yaw_key * 0.02))

    # Update filters with adjusted smoothing coefficients
    # Increased smoothing during turns
    smoothing = 0.975 + (0.01 * abs(yaw_rate))  # Increase smoothing during turns
    smoothing = min(smoothing, 0.99)  # Cap maximum smoothing
    
    pitch_dot_filtered = (pitch_dot_filtered * smoothing) + (pitch_dot * (1 - smoothing))
    velocity_angular_filtered = (velocity_angular_filtered * smoothing) + (wheel_avg * (1 - smoothing))

    last_pitch = pitch_corrected





def sysCall_cleanup():
    # do some clean-up here
    # This function will be executed when the simulation ends
    
    ####### ADD YOUR CODE HERE ######
    # Any cleanup (if required) to take the scene back to it's original state after simulation
    # It helps in case simulation fails in an unwanted state.
    #################################
    global SIM, LEFT_JOINT, RIGHT_JOINT
    try:
        SIM.setJointTargetVelocity(LEFT_JOINT, 0)
        SIM.setJointTargetVelocity(RIGHT_JOINT, 0)
    except:
        pass

# -----------------------
# helper functions and controller calculation (module-level)
# -----------------------
def clamp(n, minn, maxn):
    if n < minn: return minn
    if n > maxn: return maxn
    return n

def calculate_lqr_velocity():
    # uses the filtered & corrected globals set in sensing
    global LQR_K, WHEEL_RADIUS, velocity_linear_set_point
    global pitch_dot_filtered, velocity_angular_filtered, last_pitch
    # note: last_pitch is already corrected for yaw heuristically
    pitch = last_pitch
    pitch_dot = pitch_dot_filtered

    velocity_linear_error = velocity_linear_set_point - (velocity_angular_filtered * WHEEL_RADIUS)
    lqr_v = LQR_K[0] * (0 - pitch) + LQR_K[1] * pitch_dot + LQR_K[2] * 0 + LQR_K[3] * velocity_linear_error
    return -lqr_v / WHEEL_RADIUS